DOC: whats new v0.20
SciTools/cartopy pull request #1867
Opened 2021-09-15 15:09 UTC by greglucas

This adds a what's new entry for v0.20.

Additionally, I added a commit that removes the Python 2 warning, and changes that to a note about how to get a speedup with PYPROJ_GLOBAL_CONTEXT, which I think is important to make people aware of.

Things to do before the v0.20 release still:
- [ ] #1646
- [ ] #1843
- [ ] #1854 

Things to consider:
- [ ] Where should we put the new documentation? Keep the old location and just live without the version selector for now, or try to move hosting to RTD (#1765)
- [ ] Removing the PROJ dependency entirely. (#1832)

2021-09-16 07:05 UTC, QuLogic commented on docs/source/whatsnew/v0.20.rst
> +* Greg Lucas reorganized the documentation updated the theme to use the
```suggestion
* Greg Lucas reorganized the documentation and updated the theme to use the
```

2021-09-16 07:07 UTC, QuLogic commented on docs/source/whatsnew/v0.20.rst
> +* John Krasting extended the InterruptedGoodeHomolosine projection to add
Can we link this?

2021-09-16 07:07 UTC, QuLogic commented on docs/source/whatsnew/v0.20.rst
> +* Ryan May updated the Geostationary projection boundary to properly
And this one?

2021-09-16 13:31 UTC, greglucas commented on docs/source/whatsnew/v0.20.rst
> +* John Krasting extended the InterruptedGoodeHomolosine projection to add
Yes, good suggestions!

2021-09-16 18:20 UTC, dopplershift requested changes

2021-09-16 18:20 UTC, dopplershift commented on docs/source/whatsnew/v0.20.rst
> +`0.20 milestone <https://github.com/SciTools/cartopy/milestone/27>`_.
Proper url is:
```suggestion
`0.20 milestone <https://github.com/SciTools/cartopy/milestone/29>`_.
```

2021-09-16 18:36 UTC, greglucas commented on docs/source/whatsnew/v0.20.rst
> +`0.20 milestone <https://github.com/SciTools/cartopy/milestone/27>`_.
Good catch! Updated.

2021-09-16 18:38 UTC, dopplershift approved these changes

2021-09-17 07:56 UTC, QuLogic commented
Please also add the dependency changes.

2021-09-17 14:07 UTC, merged